#!/bin/bash
source project.config

echo "$PDK_LOCATION"
echo "$OPENSPARC_LOCATION"
echo "$VOLTAGE_THRESHOLD"
echo "$TARGET_CORNER_SPEED"
echo "$TARGET_CORNER_TEMP"
echo "$MAX_PATHS"
echo "$AREA_EFFORT"
echo "$POWER_EFFORT"
echo "$MAP_EFFORT"
echo "$COMPILE_ULTRA"
echo "$CU_FLAGS"
echo "$CLK_PERIOD"
echo "$CLK_LATENCY"
echo "$CLK_TRANSITION"
echo "$INPUT_DELAY"
echo "$OUTPUT_DELAY"
echo "$MAX_AREA"
echo "$MAX_LOAD"
echo "$TARGET_CORNER_VOLTAGE"
echo "$TARGET_CORNER"
